---
- hosts: all
  become: yes
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   
    - name: Install docker 
      snap:
        name: docker
        classic: yes
    
    - name: Create a data container and run it
      docker_container:
        name: hello_world
        image: hello-world:latest
        pull: yes
    
