# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/ubuntu1804"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vm.provision "shell",
  inline: "
  sudo snap install docker;
  sudo systemctl start docker;
  sudo docker pull hello-world;
  sudo docker run hello-world;
"

end
